public class TestExceptionHandling {
    public static void main(String str[]) {
        int y = 0;
        int x = 1;
        
        // try block to "SEE" if an exception occurs
        try {
            int z = x / y;  // This will throw an ArithmeticException
            System.out.println("After division");
        } 
        // catch block to handle the ArithmeticException generated by division by zero
        catch (ArithmeticException ae) {
            System.out.println("Attempt to divide by 0");
        }
        
        // This will be executed after the catch block, regardless of whether an exception occurred
        System.out.println("After catch");
    }
}
